version: '3'
services:
  netcore_angular:
    image: netcore_angular:latest
    build: .
    volumes:
      - .:/netcore_angular
    ports:
      - "6000:4000"
    container_name: netcore_angular
    restart: always